datasets:
  webvid:
    data_type: images
    #build_info:
    #  storage: /path/to/webvid2.5M/
    size_img: 224
    img_transform: ["img_rand_crop"]
    size_frame: 4
    dataset: webvid2.5m
    split: train
    data_dir: '/content/drive/MyDrive/_pretrain'
    part: [0,1,2,3,4,5,6,7,8,9]
