model:
  arch: muvi

  # audio encoder
  mert_model: '/jmain02/home/J2AD007/txk47/yxm46-txk47/yinghao/MUVI/model/MERT-v1-330M'

  # Vicuna
  llama_model: '/jmain02/home/J2AD007/txk47/yxm46-txk47/yinghao/MUVI/model/7B_vicuna'

  # generation configs
  prompt: ""


