model:
  arch: muvi

  # audio encoder
  mert_model: 'm-a-p/MERT-v1-330M'

  # Vicuna
  llama_model: '/content/drive/MyDrive/model_weights/llama_weights_new/llama-2-7b-chat'

  # generation configs
  prompt: ""
