model:
  arch: muvi

  # audio encoder
  mert_model: 'MERT-v1-330M'

  # Vicuna
  llama_model: '/content/drive/MyDrive/model_weights/llama_weights_new/7B_vicuna'

  # generation configs
  prompt: ""


