model:
  arch: muvi

  # audio encoder
  mert_model: '/bask/projects/v/vjgo8416-sel-sup-aud/MUVI/model/MERT-v1-330M'

  # Vicuna
  llama_model: '/bask/projects/v/vjgo8416-sel-sup-aud/MUVI/model/7B_vicuna'

  # generation configs
  prompt: ""


